// AI Tools types and definitions

export type AITool = 
  | 'cursor' 
  | 'cursor-composer' 
  | 'cursor-chat'
  | 'chatgpt' 
  | 'claude' 
  | 'gemini' 
  | 'v0' 
  | 'replit' 
  | 'github-copilot'
  | 'copilot-chat'
  | 'perplexity'
  | 'phind'
  | 'figma-ai'
  | 'galileo-ai'
  | 'uizard-ai'
  | 'midjourney'
  | 'dalle';

export interface AIToolInfo {
  id: AITool;
  name: string;
  description: string;
  icon: string;
  useCase: string;
  howToUse: string[];
  examplePrompts: string[];
  bestFor: string[];
  tips: string[];
}

export const AI_TOOLS: Record<AITool, AIToolInfo> = {
  cursor: {
    id: 'cursor',
    name: 'Cursor',
    description: 'AI-powered code editor with chat and autocomplete',
    icon: '⌨️',
    useCase: 'Writing code, refactoring, debugging, asking questions',
    howToUse: [
      'Step 1: Install Cursor from cursor.sh',
      'Step 2: Open your project in Cursor',
      'Step 3: Press Cmd+K (Mac) or Ctrl+K (Windows) to open inline edit',
      'Step 4: Type your request and let Cursor generate code',
      'Step 5: Review the generated code',
      'Step 6: Press Tab to accept or Esc to cancel',
      'Step 7: Use Cmd+L to open chat for questions',
      'Step 8: Select code and ask Cursor to explain or refactor',
    ],
    examplePrompts: [
      'Create a React component called TodoItem that displays a todo with a checkbox',
      'Refactor this function to use async/await instead of promises',
      'Add error handling to this API call',
      'Explain what this code does',
    ],
    bestFor: [
      'Writing new code',
      'Refactoring existing code',
      'Debugging errors',
      'Understanding code',
      'Adding features',
    ],
    tips: [
      'Be specific about what you want',
      'Include context about your project',
      'Ask for explanations if code is unclear',
      'Use Cmd+K for quick edits',
      'Use Cmd+L for detailed explanations',
    ],
  },
  chatgpt: {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'OpenAI\'s conversational AI assistant',
    icon: '🤖',
    useCase: 'General coding help, explanations, problem-solving, learning concepts',
    howToUse: [
      'Step 1: Go to chat.openai.com or use the ChatGPT app',
      'Step 2: Sign up or log in to your account',
      'Step 3: Start a new conversation',
      'Step 4: Provide context about your project (language, framework, etc.)',
      'Step 5: Ask your question or describe what you need',
      'Step 6: Review the response and ask follow-up questions',
      'Step 7: Copy the code and paste into your project',
      'Step 8: Test and iterate based on ChatGPT\'s suggestions',
    ],
    examplePrompts: [
      'I\'m building a React todo app. How do I create a component that displays a list of todos?',
      'Explain how React hooks work, specifically useState and useEffect',
      'Help me debug this error: "Cannot read property \'map\' of undefined"',
      'What\'s the best way to structure a React component with TypeScript?',
      'How do I connect my React frontend to a Node.js backend API?',
    ],
    bestFor: [
      'Learning concepts',
      'Getting explanations',
      'Problem-solving',
      'Code review',
      'Architecture advice',
      'Best practices',
    ],
    tips: [
      'Provide context about your project upfront',
      'Be specific about what you want to learn',
      'Ask follow-up questions for clarification',
      'Request code examples',
      'Ask for explanations of why, not just how',
      'Use it to understand error messages',
    ],
  },
  claude: {
    id: 'claude',
    name: 'Claude (Anthropic)',
    description: 'Anthropic\'s AI assistant with strong reasoning capabilities',
    icon: '🧠',
    useCase: 'Complex problem-solving, code analysis, detailed explanations, architecture design',
    howToUse: [
      'Step 1: Go to claude.ai or use Claude in your IDE',
      'Step 2: Sign up or log in to your account',
      'Step 3: Start a new conversation',
      'Step 4: Upload code files or paste code directly',
      'Step 5: Ask detailed questions about your code',
      'Step 6: Request code improvements or refactoring',
      'Step 7: Ask for explanations of complex concepts',
      'Step 8: Review Claude\'s suggestions and implement',
    ],
    examplePrompts: [
      'Analyze this React component and suggest improvements for performance and readability',
      'Help me design the architecture for a full-stack todo application',
      'Explain the difference between server-side and client-side rendering',
      'Review this code and identify potential bugs or security issues',
      'How should I structure my API endpoints for a RESTful design?',
    ],
    bestFor: [
      'Code analysis',
      'Architecture design',
      'Complex problem-solving',
      'Detailed explanations',
      'Code review',
      'Security analysis',
    ],
    tips: [
      'Upload or paste code for better context',
      'Ask for detailed explanations',
      'Request multiple solution approaches',
      'Ask about trade-offs and best practices',
      'Use it for architectural decisions',
      'Request security considerations',
    ],
  },
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Google\'s AI assistant with multimodal capabilities',
    icon: '💎',
    useCase: 'Coding help, explanations, quick answers, learning',
    howToUse: [
      'Step 1: Go to gemini.google.com or use Google AI Studio',
      'Step 2: Sign in with your Google account',
      'Step 3: Start a new conversation',
      'Step 4: Describe your coding task or question',
      'Step 5: Provide context about your project',
      'Step 6: Review Gemini\'s response',
      'Step 7: Ask follow-up questions if needed',
      'Step 8: Copy code suggestions to your project',
    ],
    examplePrompts: [
      'How do I create a React component with TypeScript?',
      'Explain how to use async/await in JavaScript',
      'What\'s the difference between useState and useReducer in React?',
      'Help me write a function to fetch data from an API',
      'How do I set up Tailwind CSS in a React project?',
    ],
    bestFor: [
      'Quick answers',
      'Learning concepts',
      'Code generation',
      'Explanations',
      'Problem-solving',
    ],
    tips: [
      'Be clear and specific in your questions',
      'Provide project context',
      'Ask for code examples',
      'Request explanations',
      'Use it for quick reference',
    ],
  },
  v0: {
    id: 'v0',
    name: 'V0 (Vercel)',
    description: 'AI-powered UI component generator',
    icon: '🎨',
    useCase: 'Generating React components with Tailwind CSS',
    howToUse: [
      'Step 1: Go to v0.dev in your browser',
      'Step 2: Sign in with your GitHub account (free tier available)',
      'Step 3: Click "New" to create a new component',
      'Step 4: Describe the UI component you want in detail',
      'Step 5: Mention styling preferences (Tailwind CSS, colors, layout)',
      'Step 6: Wait for V0 to generate the component',
      'Step 7: Review the generated code',
      'Step 8: Click "Copy" to copy the code',
      'Step 9: Paste into your project file',
      'Step 10: Adjust imports and adapt to your project structure',
    ],
    examplePrompts: [
      'Create a modern landing page with hero section, features grid, and CTA button',
      'Build a todo list component with add, edit, and delete functionality',
      'Design a user profile card with avatar, name, and bio',
      'Make a responsive navigation bar with mobile menu',
    ],
    bestFor: [
      'UI components',
      'Landing pages',
      'Forms',
      'Cards and layouts',
      'Quick prototypes',
    ],
    tips: [
      'Describe the visual design you want',
      'Mention specific styling (Tailwind, colors, etc.)',
      'Include responsive requirements',
      'Ask for accessibility features',
      'Copy and adapt to your project',
    ],
  },
  replit: {
    id: 'replit',
    name: 'Replit',
    description: 'Online IDE with AI assistant',
    icon: '💻',
    useCase: 'Quick prototyping, testing code, learning',
    howToUse: [
      'Step 1: Go to replit.com and sign up',
      'Step 2: Click "Create Repl" to start a new project',
      'Step 3: Choose your template (React, Node.js, etc.)',
      'Step 4: Open the AI chat panel (Cmd+L or click AI icon)',
      'Step 5: Ask questions or request code',
      'Step 6: Let AI generate code snippets',
      'Step 7: Review and accept the code',
      'Step 8: Run and test immediately in the browser',
      'Step 9: Iterate based on results',
    ],
    examplePrompts: [
      'Set up a React project with TypeScript',
      'Create an API endpoint that returns JSON data',
      'Add authentication to this app',
      'Help me debug this error',
    ],
    bestFor: [
      'Quick prototypes',
      'Learning new technologies',
      'Testing ideas',
      'Collaborative coding',
    ],
    tips: [
      'Use it for experimentation',
      'Great for learning',
      'Test before copying to main project',
      'Use AI chat for help',
    ],
  },
  'github-copilot': {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'AI pair programmer in your editor',
    icon: '🤖',
    useCase: 'Autocomplete, code suggestions, function generation',
    howToUse: [
      'Step 1: Install GitHub Copilot extension in VS Code or your IDE',
      'Step 2: Sign in with your GitHub account',
      'Step 3: Start typing code normally',
      'Step 4: Copilot will show suggestions (gray text)',
      'Step 5: Press Tab to accept a suggestion',
      'Step 6: Press Esc to dismiss',
      'Step 7: Write comments describing what you want',
      'Step 8: Let Copilot generate the code based on comments',
      'Step 9: Review and modify as needed',
    ],
    examplePrompts: [
      '// Function to fetch user data from API',
      '// Component that displays a list of items',
      '// Hook to manage form state',
      '// Test for this component',
    ],
    bestFor: [
      'Autocomplete',
      'Boilerplate code',
      'Common patterns',
      'Test generation',
    ],
    tips: [
      'Write descriptive comments',
      'Accept suggestions that look good',
      'Review generated code',
      'Use for repetitive tasks',
      'Let it complete your thoughts',
    ],
  },
  'cursor-composer': {
    id: 'cursor-composer',
    name: 'Cursor Composer',
    description: 'Multi-file code generation in Cursor',
    icon: '🎼',
    useCase: 'Generating multiple related files at once',
    howToUse: [
      'Press Cmd+I to open Composer',
      'Describe the feature you want to build',
      'Cursor generates all related files',
      'Review and accept changes',
    ],
    examplePrompts: [
      'Create a user authentication system with login, register, and logout',
      'Build a todo app with components, API routes, and database schema',
      'Add a shopping cart feature with add, remove, and checkout',
    ],
    bestFor: [
      'Multi-file features',
      'Full feature implementation',
      'Architecture changes',
      'Complex refactoring',
    ],
    tips: [
      'Describe the complete feature',
      'Mention all files you need',
      'Include relationships between files',
      'Review all generated code',
    ],
  },
  'cursor-chat': {
    id: 'cursor-chat',
    name: 'Cursor Chat',
    description: 'AI assistant chat in Cursor',
    icon: '💬',
    useCase: 'Asking questions, getting help, code explanations',
    howToUse: [
      'Step 1: Open Cursor editor',
      'Step 2: Press Cmd+L (Mac) or Ctrl+L (Windows) to open chat',
      'Step 3: Ask questions about your code',
      'Step 4: Reference specific files or code blocks',
      'Step 5: Get explanations and suggestions',
      'Step 6: Ask for code improvements',
      'Step 7: Follow up with more questions',
    ],
    examplePrompts: [
      'How do I connect this React component to my API?',
      'What\'s the best way to handle errors in this function?',
      'Explain this code block to me',
      'How can I optimize this component?',
    ],
    bestFor: [
      'Learning',
      'Debugging',
      'Code reviews',
      'Getting help',
    ],
    tips: [
      'Ask specific questions',
      'Reference your code',
      'Ask for best practices',
      'Request explanations',
    ],
  },
  'copilot-chat': {
    id: 'copilot-chat',
    name: 'GitHub Copilot Chat',
    description: 'Chat interface in GitHub Copilot',
    icon: '💭',
    useCase: 'Asking questions, getting code suggestions, explanations',
    howToUse: [
      'Step 1: Install GitHub Copilot extension in VS Code',
      'Step 2: Open Copilot Chat panel (Cmd+Shift+P, then "GitHub Copilot: Open Chat")',
      'Step 3: Ask questions about your code',
      'Step 4: Reference files or code selections',
      'Step 5: Get code suggestions and explanations',
      'Step 6: Apply suggestions to your code',
    ],
    examplePrompts: [
      'How do I implement authentication in this React app?',
      'Explain how this function works',
      'Suggest improvements for this component',
      'Help me debug this error',
    ],
    bestFor: [
      'Code explanations',
      'Getting suggestions',
      'Learning',
      'Debugging',
    ],
    tips: [
      'Reference your code',
      'Ask specific questions',
      'Request code examples',
      'Ask for best practices',
    ],
  },
  perplexity: {
    id: 'perplexity',
    name: 'Perplexity AI',
    description: 'AI-powered search and research assistant',
    icon: '🔍',
    useCase: 'Research, finding solutions, learning from web sources',
    howToUse: [
      'Step 1: Go to perplexity.ai',
      'Step 2: Sign up or log in',
      'Step 3: Ask your coding question',
      'Step 4: Perplexity searches the web and provides answers',
      'Step 5: Review sources and code examples',
      'Step 6: Use the information in your project',
    ],
    examplePrompts: [
      'What\'s the best way to handle state management in React in 2024?',
      'How do I set up authentication with JWT tokens?',
      'What are the latest best practices for TypeScript?',
    ],
    bestFor: [
      'Research',
      'Finding solutions',
      'Learning from web',
      'Staying updated',
    ],
    tips: [
      'Ask current questions',
      'Review sources provided',
      'Use for research',
      'Check for latest practices',
    ],
  },
  phind: {
    id: 'phind',
    name: 'Phind',
    description: 'AI search engine for developers',
    icon: '🔎',
    useCase: 'Finding solutions, code examples, debugging help',
    howToUse: [
      'Step 1: Go to phind.com',
      'Step 2: Type your coding question',
      'Step 3: Phind searches and provides answers',
      'Step 4: Review code examples and explanations',
      'Step 5: Use the solutions in your project',
    ],
    examplePrompts: [
      'How do I fix "Cannot read property of undefined" error in React?',
      'What\'s the best way to structure a Node.js API?',
      'How do I implement pagination in a React component?',
    ],
    bestFor: [
      'Finding solutions',
      'Debugging help',
      'Code examples',
      'Quick answers',
    ],
    tips: [
      'Be specific in questions',
      'Review multiple solutions',
      'Test code examples',
      'Ask follow-up questions',
    ],
  },
  'figma-ai': {
    id: 'figma-ai',
    name: 'Figma AI',
    description: 'AI-powered design assistant in Figma for UI/UX design',
    icon: '🎨',
    useCase: 'Creating UI designs, wireframes, components, design systems',
    howToUse: [
      'Step 1: Open Figma (figma.com) and create a new file',
      'Step 2: Select the AI tools in the toolbar or use Figma plugins',
      'Step 3: Use "Make Design" or "Generate UI" features',
      'Step 4: Describe your UI component or page design',
      'Step 5: Figma AI generates design elements, layouts, and components',
      'Step 6: Refine the generated design manually',
      'Step 7: Export design specs for developers',
      'Step 8: Use AI to generate color palettes, typography, and spacing',
    ],
    examplePrompts: [
      'Create a todo app interface with a header, input field, and list of todos',
      'Design a modern login page with email and password fields',
      'Generate a dashboard layout with sidebar navigation and main content area',
      'Create a mobile app screen for a todo list with Material Design',
    ],
    bestFor: [
      'UI/UX design',
      'Wireframing',
      'Component design',
      'Design systems',
      'Prototyping',
      'Visual design',
    ],
    tips: [
      'Be specific about layout and components',
      'Mention design style (Material, iOS, custom)',
      'Describe color schemes and typography preferences',
      'Ask for responsive designs',
      'Use for design inspiration and rapid prototyping',
      'Export designs to code with Figma plugins',
    ],
  },
  'galileo-ai': {
    id: 'galileo-ai',
    name: 'Galileo AI',
    description: 'AI that generates UI designs from text descriptions',
    icon: '🚀',
    useCase: 'Rapid UI generation, design mockups, component creation',
    howToUse: [
      'Step 1: Go to galileo.ai or use the Figma plugin',
      'Step 2: Sign in with your account',
      'Step 3: Describe the UI you want to create',
      'Step 4: Specify design style, colors, and layout preferences',
      'Step 5: Galileo generates high-fidelity UI designs',
      'Step 6: Review and iterate on the generated designs',
      'Step 7: Export designs to Figma or download as images',
      'Step 8: Use generated designs as reference for development',
    ],
    examplePrompts: [
      'Create a todo app interface with a clean, modern design',
      'Design a dashboard with sidebar, header, and main content grid',
      'Generate a mobile-first todo list interface with dark mode',
      'Create a landing page with hero section, features, and CTA',
    ],
    bestFor: [
      'Rapid prototyping',
      'UI mockups',
      'Design inspiration',
      'Component generation',
      'Layout design',
      'Visual concepts',
    ],
    tips: [
      'Be descriptive about the UI elements you need',
      'Specify design style (modern, minimalist, colorful, etc.)',
      'Mention target platform (web, mobile, tablet)',
      'Describe user flow and interactions',
      'Request multiple variations',
      'Use for quick design exploration',
    ],
  },
  'uizard-ai': {
    id: 'uizard-ai',
    name: 'Uizard AI',
    description: 'AI-powered design tool that converts sketches and text to UI designs',
    icon: '✨',
    useCase: 'Design from sketches, wireframes, text-to-design conversion',
    howToUse: [
      'Step 1: Go to uizard.io and sign in',
      'Step 2: Create a new project',
      'Step 3: Use "Text to Design" feature',
      'Step 4: Describe your UI in natural language',
      'Step 5: Upload sketches or use AI to generate from text',
      'Step 6: Uizard converts to editable UI designs',
      'Step 7: Customize colors, fonts, and layouts',
      'Step 8: Export designs or generate code',
    ],
    examplePrompts: [
      'Create a todo app with a header, input form, and scrollable todo list',
      'Design a settings page with sections for profile, notifications, and preferences',
      'Generate a mobile app screen for adding and managing todos',
      'Create a web dashboard with navigation sidebar and content cards',
    ],
    bestFor: [
      'Sketch to design',
      'Wireframe conversion',
      'Rapid UI generation',
      'Design from text',
      'Prototyping',
      'Design automation',
    ],
    tips: [
      'Describe UI elements clearly',
      'Mention layout structure (grid, list, card)',
      'Specify component types (buttons, inputs, cards)',
      'Request responsive designs',
      'Use for quick design iterations',
      'Combine with code generation tools',
    ],
  },
  'midjourney': {
    id: 'midjourney',
    name: 'Midjourney',
    description: 'AI image generation for design inspiration and visual concepts',
    icon: '🖼️',
    useCase: 'Design inspiration, visual concepts, mood boards, UI mockups',
    howToUse: [
      'Step 1: Join Midjourney Discord server',
      'Step 2: Use /imagine command',
      'Step 3: Describe your design concept or UI inspiration',
      'Step 4: Add style parameters (--style, --v, etc.)',
      'Step 5: Midjourney generates 4 image variations',
      'Step 6: Upscale or create variations of selected images',
      'Step 7: Use generated images as design inspiration',
      'Step 8: Reference colors, layouts, and styles in your designs',
    ],
    examplePrompts: [
      'Modern minimalist todo app interface, clean design, soft colors, --style ui',
      'Cyberpunk dashboard design, neon colors, dark theme, futuristic UI',
      'Mobile app screen design, iOS style, todo list interface, --v 6',
      'Web application UI, modern design, gradient backgrounds, --style raw',
    ],
    bestFor: [
      'Design inspiration',
      'Visual concepts',
      'Mood boards',
      'Color palettes',
      'Style exploration',
      'Creative direction',
    ],
    tips: [
      'Use --style ui for UI-focused designs',
      'Specify color schemes and themes',
      'Mention design style (minimalist, colorful, dark, etc.)',
      'Request multiple variations',
      'Use for inspiration, not direct implementation',
      'Combine with design tools for implementation',
    ],
  },
  'dalle': {
    id: 'dalle',
    name: 'DALL-E',
    description: 'OpenAI\'s AI image generator for design concepts and inspiration',
    icon: '🎭',
    useCase: 'UI design concepts, visual inspiration, design mockups, creative exploration',
    howToUse: [
      'Step 1: Go to chat.openai.com or labs.openai.com',
      'Step 2: Access DALL-E through ChatGPT Plus or DALL-E interface',
      'Step 3: Describe your UI design concept in detail',
      'Step 4: Specify style, colors, layout, and components',
      'Step 5: DALL-E generates image variations',
      'Step 6: Refine prompts for better results',
      'Step 7: Download generated images',
      'Step 8: Use as design reference or inspiration',
    ],
    examplePrompts: [
      'A modern todo app interface design, clean white background, minimalist style, with input field and list of tasks',
      'Mobile app screen design for todo list, iOS style, colorful cards, dark mode option',
      'Dashboard UI design, sidebar navigation, main content area with cards, modern web design',
      'Login page design, gradient background, centered form, modern UI elements',
    ],
    bestFor: [
      'Design concepts',
      'Visual inspiration',
      'UI mockups',
      'Creative exploration',
      'Style references',
      'Color inspiration',
    ],
    tips: [
      'Be specific about UI elements and layout',
      'Mention design style and platform',
      'Describe color schemes and typography',
      'Request multiple variations',
      'Use for inspiration and reference',
      'Combine with design tools for implementation',
    ],
  },
};

export interface ToolStep {
  tool: AITool;
  whenToUse: string;
  promptTemplate: string;
  expectedOutput: string;
  validation?: string;
}

